# Generated by Django 2.0.2 on 2018-02-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.TextField()),
                ('CompanyName', models.TextField()),
                ('ContactName', models.TextField()),
                ('ContactTitle', models.TextField()),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('Region', models.TextField()),
                ('PostalCode', models.TextField()),
                ('Country', models.TextField()),
                ('Phone', models.TextField()),
                ('Fax', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('PaymentTerm', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
    
